<h3><?php echo  $US['nav-start']?></h3>
<a target="content" onclick="h(this);" href="stop.php"><?php echo  $US['nav-sserver']?></a>
<a target="content" onclick="h(this);" href="<?php echo $apanel?>/cgi-bin/includes/lang/<?php echo file_get_contents("includes/.lang");?>/rserver.cgi"><?php echo  $US['nav-rserver']?></a>
<a target="content" onclick="h(this);" href="<?php echo $apanel?>/cgi-bin/includes/lang/<?php echo file_get_contents("includes/.lang");?>/rmysql.cgi"><?php echo  $US['nav-rmysql']?></a>
<a target="content" onclick="h(this);" href="<?php echo $apanel?>/cgi-bin/includes/lang/<?php echo file_get_contents("includes/.lang");?>/smysql.cgi"><?php echo  $US['nav-smysql']?></a>
